# Generated by Django 5.1.3 on 2026-07-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="stripe_sustomer_id",
            new_name="stripe_customer_id",
        ),
    ]
