# Generated by Django 5.1.3 on 2026-06-17 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("exercise", "Exercise Plan"),
                            ("nutrition", "Nutrition Plan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NutritionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("vegetarian", "Vegetarian"),
                            ("vegan", "Vegan"),
                            ("keto", "Keto"),
                            ("paleo", "Paleo"),
                            ("mediterranean", "Mediterranean"),
                            ("standard", "Standard"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "calories_target",
                    models.PositiveIntegerField(help_text="Daily calorie target"),
                ),
                (
                    "protein_grams",
                    models.PositiveIntegerField(
                        help_text="Daily protein target in grams"
                    ),
                ),
                (
                    "carbs_grams",
                    models.PositiveIntegerField(
                        help_text="Daily carbs target in grams"
                    ),
                ),
                (
                    "fats_grams",
                    models.PositiveIntegerField(help_text="Daily fats target in grams"),
                ),
                (
                    "dietary_restrictions",
                    models.TextField(
                        blank=True, help_text="List any dietary restrictions"
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_details",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExercisePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration_weeks",
                    models.PositiveBigIntegerField(help_text="Duration in weeks"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "equipment_needed",
                    models.TextField(
                        blank=True, help_text="List of equipment required"
                    ),
                ),
                ("workouts_per_week", models.PositiveBigIntegerField(default=3)),
                (
                    "calories_burn_estimate",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Estimated calories burned per session",
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_details",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_payment_intent", models.CharField(blank=True, max_length=100)),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-purchase_date"],
                "unique_together": {("user", "product")},
            },
        ),
    ]
